### ISSUE TITLE
:redeploy does not work on 'docker', '~> 0.36.0' version

### ISSUE THREAD

**Issue by bmkgeek** [bflad/chef-docker#248]
Hello,

Docker :redeploy does not work on 'docker', '~> 0.36.0' version. Please see the error logs,

STDERR: 2014/12/12 11:18:26 Error response from daemon: Conflict, The name elasticsearch  is already assigned to 85b9d51b6a80. You have to delete (or rename) that container to be able to assign elasticsearch to a container again.

###################################
docker_image 'dockerfile/elasticsearch' do
        action :pull
        notifies :redeploy, 'docker_container[dockerfile/elasticsearch]', :immediately
 end

 # Run container exposing ports
docker_container 'dockerfile/elasticsearch' do
    detach true
    port ['9200:9200', '9300:9300']
    volume '/data:/data'
    action :run
end
#####################################

'docker', '~> 0.36.0' version
Ubuntu 14.04.1 LTS

Let me know if you have any isssue on this recipe.

Thanks
Bilal

**Comment by jperville** [comment]
Hi @bmkgeek, I encountered that one a few times lately, will allocate some time this week-end to investigate and maybe fix.

**Comment by bmkgeek** [comment]
Hi jperville,

I have fixed this issue after modified the code,
https://github.com/bflad/chef-docker/blob/master/providers/container.rb

51 action :redeploy do
52   stop if (previously_running = running?)
53    remove_container if exists?
54    run
55    new_resource.updated_by_last_action(true)
56 end

Any issue on the above codes?

**Comment by 0vertone** [comment]
Coming across this myself. Bit frustrating. Any update?

**Comment by jperville** [comment]
Hi @0vertone, sorry for being late. Yes, I still get that from time to time but rarely new (maybe my containers are too stable and don't redeploy that often anymore). Will still try to find time for reproduce and fix but my time is scarce lately.

**Comment by w32-blaster** [comment]
I have the same problem. Trying to redeploy the container after the image is replaced with a newer version. 
Platform: Ubuntu 14.04
Cookbook version: 0.37

**Comment by someara** [comment]
Fixed in master
