### ISSUE TITLE
docker_image :pull fails against a private repo at hub.docker.com 

### ISSUE THREAD

**Issue by joegoggins** [bflad/chef-docker#417]
On Ubuntu 14.04 or Centos 7.1 with Docker at 1.8.1, when I do this:

    docker_registry 'https://index.docker.io/v1/' do
      username 'the-username'
      email 'theemail@email.com'
      password 'the-password'
    end

    docker_image 'the-org/the-repo' do
      tag 'latest'
      action :pull
    end

I get this error:

    Docker::Error::ArgumentError
    ----------------------------
    Must have id, got: {"id"=>nil, :headers=>{}}

Oddly, if I do `docker login` with the same credentials and then `docker pull the-org/the-repo`, the image gets pulled down exactly as expected. I've tried a number of permutations of this and observed the same cookbook failure behavior. I'm guessing it has something to do with an upstream change in the Docker Registry api that the docker-api gem fails to handle gracefully. I noticed their is a new docker-api gem release, perhaps that might encapsulate this change...I don't know.

The use case I'm shooting for is a simple one: "Use docker cookbook to pull and deploy new private images from the main Docker registry", this issue is a blocker for this. 

Let me know if I can clarify the failure I've seeing or if anyone has suggestions for work arounds!

Thanks!

**Comment by alexdeleon** [comment]
+1
Same issue here. Also on Centos 7.1.

**Comment by someara** [comment]
This should be fixed in 1.0.22.

**Comment by alexdeleon** [comment]
Hi @someara , I have tries with 1.0.22 but I still get the error. The only difference is that now the error contains the `X-Registry-Auth` header. 

```
RuntimeError
------------
Must have id, got: {"id"=>nil, :headers=>{"X-Registry-Auth"=>"XXXX"}}
```

**Comment by joegoggins** [comment]
Not sure if it's helpful, but I vaguely recall this functionality working
fine on 1.0.14, but having the issue appear in 1.0.21.
I'm really looking forward to a fix on this, the particular route I take
toward a Docker infrastructure later today or tomorrow is highly contingent
on this working, let me know if there is anything I can do to test further
or provide more details.

Thanks,

-joe

On Thu, Sep 10, 2015 at 7:41 AM, Alexander De Leon <notifications@github.com

**Comment by someara** [comment]
Ug.. I totally tested this manually here

https://github.com/bflad/chef-docker/blob/e626cffb80d84c370c6b546c4d941d54573c18fa/test/cookbooks/docker_test/recipes/image.rb#L197

I guess could set up a test user on the public hub with insecure credentials... I wonder if that's against a rule somewhere. There would be potential for abuse

**Comment by joegoggins** [comment]
Hmm, thanks for sharing--it looks like this is a private dockerhub _user_ account as opposed to a private _organization_ account. I wonder if the failure is specific to private repos associated with an organization...

**Comment by someara** [comment]
Can you try testing an isolated resource in a single chef-client run?

**Comment by joegoggins** [comment]
Sweeeet. I think you've solved it sir. The first time I attempted to verify the fix I forgot to `berks update` after bumping the docker cookbook version in metadata.rb and it failed (duh, of course it did :smile: ).  However, when I updated cookbook to latest and converged a dirt simple recipe like this:

    docker_service 'default' do
      action [:create, :start]
      version '1.8.1'
    end

    docker_registry 'https://index.docker.io/v1/' do
      username 'some-user'
      email 'some-email@email.io'
      password 'some-password'
    end

    # Pull tagged image
    docker_image 'some-org/some-image' do
      tag 'latest'
      action :pull
    end

Bliss was experienced, as this fine output popped onto my screen:

    Chef Client finished, 7/8 resources updated in 217.930666617 seconds
    Finished converging <dockerhost-ubuntu-1404> (4m34.57s).

Looks fixed to me, thanks!

**Comment by yonah-codefresh** [comment]
I'm still seeing this error on 1.0.45 trying to pull an image from a private user account on DockerHub.

I'm not specifying the registry address in the image name since DockerHub is the default.

From what I can tell, the parse_registry_host is returning the name of the repo instead of the name of the registry because it doesn't handle this default case.
Next pull_image is failing to find the correct credentials because there is no registry by that name in docker_auth.

Theoretically, I'd think the best fix would be to better check the repo value in the helper function but I worked around the problem in pull_image by falling back to index.docker.io credentials in case there is nothing more specific:
```ruby
    def pull_image
        begin
          retries ||= new_resource.api_retries
          api_timeouts

          registry_host = parse_registry_host(new_resource.repo)
          creds = node.run_state['docker_auth'] && node.run_state['docker_auth'][registry_host] || node.run_state['docker_auth']["index.docker.io"]
          original_image = Docker::Image.get(image_identifier) if Docker::Image.exist?(image_identifier)
          new_image = Docker::Image.create({ 'fromImage' => image_identifier }, creds)
        rescue Docker::Error => e
          retry unless (retries -= 1).zero?
          raise e.message
        end

        !(original_image && original_image.id.start_with?(new_image.id))
      end```

**Comment by alexdeleon** [comment]
@yonah-codefresh check that your image tag exists in DockerHub. I was getting this error which at first seem like it was an authentication error, but it was actually caused by a typo on the tag name.

**Comment by yonah-codefresh** [comment]
@alexdeleon The image definitely exists. I added some debug logs and see that the creds var is empty when trying to pull. Also, with the workaround I mentioned the images get pulled like clockwork.

**Comment by someara** [comment]
Is there any chance your workaround could end up in Pull Request format?
=)

**Comment by someara** [comment]
Thanks Yonah! Merged and released as v1.0.47

**Comment by bhanushrestha** [comment]
I know this was said to be fixed but still when i did the same as shown by @joegoggins for pulling the private repository i got an error as such:

Docker::Error::ArgumentError
   Must have id, got: {"id"=>nil, :headers=>{"X-Registry-Auth"=>"

Can anybody help?
